name: Build & Upload to Firebase (iOS + Android)

on:
  push:
    branches: [release] # หรือเปลี่ยนเป็น main/dev ตามที่คุณต้องการ

jobs:
  ios-build:
    name: 🚀 iOS Build & Firebase Upload
    runs-on: macos-latest

    steps:
      - name: 🧾 Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: yarn install

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler: latest

      - name: 🚀 Install Fastlane
        run: gem install fastlane -NV

      - name: 📚 Install CocoaPods
        run: pod install
        working-directory: ios

      - name: 🏗️ Run Fastlane (iOS)
        run: bundle exec fastlane ios beta_ios
        working-directory: fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  android-build:
    name: 🤖 Android Build & Firebase Upload
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: yarn install

      - name: ☕️ Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: 🚀 Install Fastlane
        run: gem install fastlane -NV

      - name: 🔐 Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: 🏗️ Run Fastlane (Android)
        run: fastlane android beta_android
        working-directory: fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
