name: Recommended Movies App

on:
  push:
    branches: [release]

jobs:
  ios-build:
    name: iOS Build & Firebase Upload
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install Pods
        run: cd ios && pod install

      - name: Run Fastlane (iOS)
        run: cd ios && fastlane beta
        env:
          FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  android-build:
    name: Android Build & Firebase Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Restore Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Run Fastlane (Android)
        run: cd android && fastlane beta
        env:
          FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
